### ISSUE TITLE
Step 5 should mention importing ActorDSL._

### ISSUE THREAD

**Issue by propensive** [scala/actors-migration#2]
With code compiling after following steps 1-4, this fails at Step 5 due to ActWithStash not being available. My presumed solution was to import ActorDSL._. Although the list of imports is "not exhaustive", at least ActorDSL._ should be listed.

**Comment by vjovanov** [comment]
Addressed by https://github.com/scala/scala.github.com/pull/183. 

Thanks!

**Comment by vjovanov** [comment]
Addressed by https://github.com/scala/scala.github.com/pull/183

Thanks, feedback is valuable.
