### ISSUE TITLE
Minor gotcha in Step 5

### ISSUE THREAD

**Issue by locutius** [scala/actors-migration#9]
This is not a bug or a problem with the migration guide; in fact, the migration guide was a terrific help.  But my mistake may provide a helpful warning to others.  

I just completed the migration to Akka but I wasted a lot of time on one stupid error.  In creating a variable to hold the ActorSystem, I placed it in the root ancestor of my Actors.  Of course, this meant that each Actor used its own ActorSystem.  Comparing Actors then didn't work because actors in different systems with similar names all compared as equal.  This type of issue was not be caught by earlier steps because they don't implement the ActorSystem.  When my code didn't work at all, I had to painstakingly trace through the code to find the problem.

The ActorSystem is not something that those using Scala Actors are used to, so it might help others to provide a warning to place the ActorSystem reference in an object, rather than a class.

**Comment by vjovanov** [comment]
Thanks for reporting this issue. It has been addressed here: 
  https://github.com/scala/scala.github.com/pull/437
